Issue3 save rss data
RafaX8/PruebaRSS pull request #7
Opened 2022-11-30 15:47 UTC by RafaX8

## Description de la tarea

Se pide implementar las clases necesarias para guardar una fuente RSS (url, name) introducido por el usuario.

## ¿Cómo se ha implementado?

Se ha implementado una estructura de archivos en la capa de datos local, haciendo uso también de Either para el manejo de errores.

Para el almacenamiento de datos en el dispositivo físico (local), se ha implementado SharedPreferences. Con este modelo, se crean archivos XML en la memoria física del dispositivo donde se almacenan los datos de cada objeto Rss. Se ha implementado también, por lo tanto, una interfaz KSerializer con Gson para parsear información json a String y viceversa.
> Ya que no se ha implementado RoomDatabase para la solución del ejercicio, no se han utilizado coroutines. Si es recomendable o incluso necesario para el futuro de la app, se actualizará con la implementación de Room.

La estructura ha sido la siguiente:

1.  En Domain
- Se han realizado un par de cambios para implementar varias funciones a la interfaz DomainRepository, así como implementar Either.
2. En Data 
- RssDataRepository: Es una clase que hereda de DomainRepository (por ello los cambios mencionados anteriormente) que gestiona qué fuente de datos trabaja con la información (local o remote, siendo local la única implementada por el momento, y por tanto, la única que recibe por parámetro). 
3. En Data > Local
- Models --> donde se encuentran los modelos de data class para los rss de la fuente de datos local.
- Mapper --> archivo con las funciones de extensión encargadas de mappear las data class de local a domain y viceversa.
- RssLocalDataSource: Interfaz con las funciones que deberán implementar las diferentes fuentes de datos locales.
4. En Data > Local > XML
- RssXmlLocalDataSource: Clase que recibe un SharedPreferences y el serializador (KSerializer, en este caso Gson) con el que va a trabajar y hereda de RssLocalDataSource. Aquí es donde se aplica el código encargado de guardar o recoger la información del archivo .xml guardado en local.

## Keywords

Either, Gestión de errores, Gestión de datos, Local, Herencia, Repositories, Serialización, etc.

## Screenshots or Video

Test realizado:
![image](https://user-images.githubusercontent.com/104196849/204834755-2c84a7fd-c47d-43d2-bf81-c4ecd6d81969.png)
Resultado de las pruebas: Output del fichero xml y por consola.
![image](https://user-images.githubusercontent.com/104196849/204834540-109ec98f-1aaf-40dc-bbcd-96070e195f5f.png)

## Objetivos

RA-6 Programa clases específicas de acceso a datos de distintas fuentes: Locales y Remotas.

- [X] El alumno valora las ventajas e inconvenientes de implementar la capa de datos en una aplicación.
- [X] El alumno identifica la fuente de datos correcta para un determinado problema.
- [X] El alumno programa un LocalDataSource que gestione información almacenada en ficheros SharedPreferences.
(Firebase).
- [X] El alumno programa un LocalDataSource que gestione información almacenada en una base de datos XML/Documentos (DataStore).
- [X] El alumno prueba y documenta las clases de fuentes de datos desarrolladas usando Pull Requests.
- [X] El alumno sabe manejar las concreciones desarrolladas de LocalDataSource y RemoteDataSource en una clase DataRepository e integrarlas en una aplicación Android.

2022-12-02 10:50 UTC, MiM14 requested changes
Buenas Rafa, te dejo unos comentarios de cosas que considero importantes. Además de comentarte un par de cosas por aquí.
En primer lugar, por experiencia propia y comentarios tanto de Chema como de otro compañero es importante que no añadas cosas que no forman parte del ticket. Me explico, cada ticket tiene una estimación y esta va asociada a las tareas a realizar, si añades más de lo que toca no estas haciendo una estimación correcta.
En tu caso no solo implementas un ticket, implementas estos 3:

- [Guardar RSS data](https://github.com/IESAM-DAM/rss-aggregator/issues/8)
- [Recuperar RSS domain](https://github.com/IESAM-DAM/rss-aggregator/issues/11)
- [Recuperar RSS data](https://github.com/IESAM-DAM/rss-aggregator/issues/14)

Y con respecto al otro comentario, no veo necesario crear un 2 modelos y un mapper, ni tampoco crear un objeto para serializarlo en la linea siguiente.

Espero que te sirvan mis comentarios, si necesitas cualquier otra cosa o charlar sobre mi corrección me dices.

2022-12-02 16:32 UTC, RafaX8 commented
He realizado cambios en el código relacionados con lo que mencionaba Ismael. La verdad algunas cosas son errores que no sé por qué me he colado, tonterías como el modelo o el mapper que simplemente no tenían cabida.

Los cambios realizados son esencialmente sustracciones de código que no aplica en este issue y correcciones en las funciones.

### Screenshots
Test realizado:
![image](https://user-images.githubusercontent.com/104196849/205339723-a514046a-48a7-4472-9ae8-a4de58e36725.png)
Resultado de las pruebas: Output del fichero xml.
![image](https://user-images.githubusercontent.com/104196849/205340019-905b9ed1-1dbe-4ff2-bbb8-d36e002118ad.png)

2022-12-02 16:37 UTC, RafaX8 commented
He implementado los cambios sugeridos por Ismael, esencialmente sustracción de código que no aplicaba para este issue o que no es necesario en la app. También se han realizado correcciones de código.

### Screenshots
Test Realizado:
![image](https://user-images.githubusercontent.com/104196849/205341185-23a991ba-5e86-4f3e-b2d1-ea72abe43144.png)
Resultado visible en el fichero XML:
![image](https://user-images.githubusercontent.com/104196849/205341318-04792e94-05a1-4125-8a41-6d3680950193.png)

2022-12-02 16:43 UTC, MiM14 approved these changes
Tiene buena pinta.
Buen trabajo Rafa, seguimos así🚀

2022-12-19 19:25 UTC, josem-perram approved these changes
🚀  La documentación de la PR está genial.

2022-12-19 19:32 UTC, merged